// @ts-nocheck
// このファイルは自動生成されます。手編集しないでください（GEN-03）。
// 生成: `pnpm generate:bindings`
// イベント未使用時に生じる未使用シンボルの警告を避けるため型チェック対象から外す。

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * サンプルコマンド。フロントの型付き呼び出し（tauri-specta, RS-05）を実演する。
 */
async greet(name: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * コマンド層の統一エラー型。`app_core::CoreError` をそのまま包み、フロントには
 * serde を通じて型付きで伝わる（RS-04）。コマンド内で `unwrap()` / `expect()` は使わず、
 * 必ずこの型に変換して `Result` として返すこと（レビュー観点 §2）。
 */
export type AppError = { kind: "Core"; message: CoreError } | { kind: "Io"; message: string }
/**
 * アプリ全体で共有する統一エラー型（RS-04）。
 * 
 * `crates/core` の全ての公開関数はこの型（または個別の `thiserror` 型を経由してこの型へ
 * 変換されるもの）を返す。`src-tauri` のコマンド層はこれを `serde` でフロントへシリアライズする。
 */
export type CoreError = { kind: "InvalidInput"; message: string } | { kind: "NotFound"; message: string } | { kind: "Internal" }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
